# Generated by Django 3.0.4 on 2020-06-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidop', models.CharField(max_length=20)),
                ('apellidom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('universidad', models.CharField(max_length=50)),
                ('fechaderegistro', models.DateTimeField(auto_now_add=True)),
                ('fechademodificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
