# Generated by Django 3.0.4 on 2020-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['fechaderegistro']},
        ),
        migrations.AddField(
            model_name='registro',
            name='opcion',
            field=models.CharField(default=' ', max_length=50, verbose_name='Paquete seleccionado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='fechademodificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fechaderegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
