# Generated by Django 3.0.4 on 2020-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20200617_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='pagado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pago confirmado')], default='Pendiente de pago', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='opcion',
            field=models.CharField(choices=[('Curso Valuacion de bienes distintos a la tierra', 'Curso Valuación de bienes distintos a la tierra $1,375.00 MXN'), ('Curso Valuacion de inmuebles rusticos con presion urbana', 'Curso Valuación de inmuebles rústicos con presión urbana $1,375.00 MXN'), ('Curso Valuacion economica de impacto ambiental por el Metodo de valoracion contingente', 'Curso Valuación económica de impacto ambiental por el Método de Valoración Contingente $1,375.00 MXN'), ('Simposio y curso', 'Simposio y curso $2,500.00 MXN')], max_length=100, verbose_name='Paquete seleccionado'),
        ),
    ]
