# Generated by Django 3.0.4 on 2020-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20200618_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='pagado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pago confirmado')], default='pendiente', max_length=50),
        ),
    ]
