# Generated by Django 3.0.4 on 2020-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20200618_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
