# Generated by Django 3.0.4 on 2020-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20200702_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='apellidom',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='apellidop',
        ),
        migrations.AddField(
            model_name='registro',
            name='calle',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='cfdi',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='registro',
            name='colonia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='formadepago',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registro',
            name='metododepago',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registro',
            name='numeroexterior',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='numerointerior',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='registro',
            name='pais',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='rfc',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
