# Generated by Django 3.0.4 on 2020-07-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20200716_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='opcion',
            field=models.CharField(choices=[('Simposio', 'Asistencia al simposio $1,595.00 MXN'), ('Curso Valuacion de bienes distintos a la tierra', 'Curso Valuación de bienes distintos a la tierra $1,595.00 MXN'), ('Curso Valuacion de inmuebles rusticos con presion urbana', 'Curso Valuación de inmuebles rústicos con presión urbana $1,595.00 MXN'), ('Curso Valuacion economica de impacto ambiental por el Metodo de valoracion contingente', 'Curso Valuación económica de impacto ambiental por el Método de Valoración Contingente $1,595.00 MXN'), ('Simposio y curso', 'Simposio y curso $2,900.00 MXN')], max_length=100, verbose_name='Paquete seleccionado'),
        ),
    ]
