# Generated by Django 3.0.4 on 2020-08-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20200803_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cfdi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='formadepago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='metododepago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
