# Generated by Django 3.0.4 on 2020-04-22 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['-creado'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='galeria',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
